### ISSUE TITLE
amapGeocode is not so slow, at least, it can be faster

### ISSUE THREAD

**Issue by womeimingzi11** [xiaojunlin/gaodemap#1]
Hi Dr.Lin, I am the author of amapGeocode.

Am I so happy to see a benchmark between amapR and amapGeocode, and I do learn a lot from your fantastic project. 

However, I believe the benchmark is little bit unfair. amapGeocode does support parallel operation after version 0.6, however, some `future` operation should be applied. It is not a bug, but a design. Because there are some consideration in compatibility and modification.

Hence, to compare  `amapGeocode::getCoord` and `amapR::geocoord` directly is not so meaningful.

**Comment by womeimingzi11** [comment]
To tell the truth, I believe the speed amapR and amapGeocode may be the consistent speed, after all, the main limitation comes from the AutoNavi API rather than performance of machine or script.

But a scientific method is still needed.

Cheers.

**Comment by xiaojunlin** [comment]
Hi, Dr. Chen.

Thanks for your comments. I am glad to hear that `amapGeocode` support parallel operation after version 0.6. The benchmarking result was generated using the old version of `amapGeocode`, which is indeed out of date and unfair. After using the latest version of `amapGeocode` (version 0.6.0)  in CRAN, I really appreciate your great work in the package improvement. 

Since both  `amapR` and `amapGeocode` are improving continuously, the meaning of cross-sectional benchmarking may be limited. Therefore, I have removed the benchmarking result from the README document. 

As for the speed of two packages, users can find the answer in practice.

**Comment by womeimingzi11** [comment]
Maybe we can make some comparisos between `amapR` and `amapGeocode`, not for competition or any other purpose, but just for some different options. For instance, `amapR` is really user-friendly and out of the box, this may not be the philosophy of `amapGeocode`, but really inspired me significantly!
